// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzsupjftqiwealmgkqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6c3VwamZ0cWl3ZWFsbWdrcXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTkzMzMsImV4cCI6MjA2NjY3NTMzM30.QsE6pF1dV69fPDAzGREDFaKk_TU9fsLmLhYt3uM2N0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});